### PR TITLE
update Push Jobs HA instructions

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: a404a2e0-483f-45cb-9255-3abc7311d346 approved by: @jamescott

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jeremiahsnapp** [comment]
@delivery deliver

**Comment by jamescott** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: a404a2e0-483f-45cb-9255-3abc7311d346 delivered by: @jamescott

**Pull request merged**
