### PR TITLE
remove /default

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Failed to approve change: 3d586154-a1ef-4ab9-928e-112995f678b7 @jamescott

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Failed to approve change: 3d586154-a1ef-4ab9-928e-112995f678b7 @jamescott

**Pull request merged**
