### PR TITLE
Add 'includes' to the description of kitchen.yml.

### PR DESCRIPTION
**Pull request by randomcamel**

### CODE REVIEW

**Comment by bookshelfdave** [comment]
should `includes` and `excludes` mention that they take a list?

**Comment by jamescott** [comment]
What is the syntax for the list? @metadave

**Comment by jamescott** [comment]
(and yes, they should)

**Comment by bookshelfdave** [comment]
simple yaml lists I believe:

```
...
    excludes:
      - debian-7.1.0
      - foo
      - bar
```

**Pull request merged**
