### PR TITLE
Add back GA outbound link tracking code

### PR DESCRIPTION
**Pull request by Padgett**
Oops...

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by cwebberOps** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 0f9fdafa-565f-4db6-b107-7ec13f5b9106 approved by: @cwebberOps

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by Padgett** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 0f9fdafa-565f-4db6-b107-7ec13f5b9106 delivered by: @Padgett

**Pull request merged**
