### PR TITLE
Document data bag item comment support

### PR DESCRIPTION
**Pull request by ekrupnik**

### CODE REVIEW

**Comment by jamescott** [comment]
Thank you! Am going to make a couple of edits to that page, FYI.

james

**Comment by ekrupnik** [comment]
Thanks @jamescott

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/8a3b9395e4ef9be9daaabfea391d2d480091ff43

^^ just made it look like other topics, with regard to the where, bullet bullet pattern.

**Comment by ekrupnik** [comment]
:+1: Thanks again @jamescott

**Pull request merged**
