### PR TITLE
point to custom_resources.html

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 59df89df-b8e6-44f3-a06b-16a0245a2dfd approved by: @jamescott

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jamescott** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 59df89df-b8e6-44f3-a06b-16a0245a2dfd delivered by: @jamescott

**Pull request merged**
