### PR TITLE
Adds slack handler

### PR DESCRIPTION
**Pull request by spuder**

### CODE REVIEW

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Failed to approve change: c4593d6f-104e-41a0-92b8-7bdb160b5200
  Change must pass verify before approving. @jamescott

**Comment by jamescott** [comment]
@delivery review

**Comment by chef-delivery** [comment]
Failed to review change: c4593d6f-104e-41a0-92b8-7bdb160b5200 @jamescott

**Comment by jamescott** [comment]
OK, well this will get the change in there:

https://github.com/chef/chef-web-docs/pull/717

Thanks for sending it in!

**Pull request closed without merging**
