### PR TITLE
Update design for Docs Nav search bar

### PR DESCRIPTION
**Pull request by magwalk**
There had been some complaints about the search bar not being readable as a search bar, this changes it to a more intuitive design that doesn't blend in with the other UI elements.

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: f3f635fb-298c-4555-a239-0b1a0b3ba531 approved by: @jamescott

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jamescott** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Failed to deliver change: f3f635fb-298c-4555-a239-0b1a0b3ba531
  Change is already delivered. @jamescott

**Pull request merged**
