### PR TITLE
add bower

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 3a912ff9-b66d-40a5-81ac-c85292229513 approved by: @jamescott

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jamescott** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 3a912ff9-b66d-40a5-81ac-c85292229513 delivered by: @jamescott

**Pull request merged**
