### PR TITLE
Remove surplus (and incorrect) comma from Chef Server tiered deployment ...

### PR DESCRIPTION
**Pull request by kwilczynski**
...examples.

Signed-off-by: Krzysztof Wilczynski krzysztof.wilczynski@linux.com

### CODE REVIEW

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/71ad448ad6be69436d7c6db32eae666f2899e759

Looks like we just crossed paths ^^^ that is the same fix :)

**Comment by kwilczynski** [comment]
@jamescott indeed, we have crossed the streams :) Although, I fixed the one with `drbd` too.
I will re-base if you want?

**Comment by kwilczynski** [comment]
@jamescott should be fine now.

**Comment by kwilczynski** [comment]
@jamescott actually, it's not. Does not like me doing force push, fair enough. I will open another PR.

**Pull request closed without merging**
