### PR TITLE
Added context to knife bootstrap instructions

### PR DESCRIPTION
**Pull request by hosh**
It is not obvious from the the knife bootstrap documentation that you `knife bootstrap` will SSH onto the target machine. I have expanded the first paragraph to explicitly state that and provide enough context for the rest of the documentation. Hopefully, people coming in cold will not try to run `knife bootstrap` on the node machine like I did.

### CODE REVIEW

**Comment by stevendanna** [comment]
What do you mean by "and (if the operating system is not |ubuntu|) the operating system running on the target system."?  The chef-full bootstrap template (which is used by default) should work on all omnibus-supported operating systems without the user supplying additional information.

**Comment by hosh** [comment]
That was in the original, I have no idea what the original author meant by that. I can just take that out and mention omnibus.

**Comment by stevendanna** [comment]
Ah, my apologies, misread that diff.

**Comment by hosh** [comment]
Eh, it just means the docs needed to be updated, might as well :-)

**Pull request merged**
