### PR TITLE
%w => %W

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: b96b8b4c-e966-4825-8706-4a9fb7b79a5f approved by: @jamescott

**Comment by jamescott** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Failed to deliver change: b96b8b4c-e966-4825-8706-4a9fb7b79a5f
  Change must pass acceptance before delivering. @jamescott

**Comment by jamescott** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Failed to deliver change: b96b8b4c-e966-4825-8706-4a9fb7b79a5f
  Change is already delivered. @jamescott

**Pull request merged**
