### PR TITLE
fix paths in makefile

### PR DESCRIPTION
**Pull request by jamescott**
12-6 should be 12-6, 12-5 should be 12-5 :)

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: ccf6fd9f-1ee2-4356-b8ed-691059e17192 approved by: @jamescott

**Comment by cwebberOps** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Failed to approve change: ccf6fd9f-1ee2-4356-b8ed-691059e17192
  Change is already merged. @cwebberOps

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jamescott** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: ccf6fd9f-1ee2-4356-b8ed-691059e17192 delivered by: @jamescott

**Pull request merged**
