### PR TITLE
strings need to be neutral

### PR DESCRIPTION
**Pull request by jamescott**
to both organization and environment

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 89170201-2af7-4b32-a823-5cadf4fb9e7b approved by: @jamescott

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jamescott** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 89170201-2af7-4b32-a823-5cadf4fb9e7b delivered by: @jamescott

**Pull request merged**
