### PR TITLE
CHEF-2641 changed --no-editor to --disable-editing.

### PR DESCRIPTION
**Pull request by stevendanna**
In order to work around a bug in the underlying option parser, we
changed --no-editor to --disable-editing.  This change should be
reflected in the documentation.

### CODE REVIEW

**Comment by jamescott** [comment]
I fixed this globally; this merge request can be deleted.

**Comment by stevendanna** [comment]
I'm still seeing this incorrect in a number of locations.  Might want to `grep -r` for no-editor. :)

**Comment by jamescott** [comment]
This is fixed now.

**Comment by stevendanna** [comment]
Note that the short option is now -d rather than -n.

**Pull request closed without merging**
