### PR TITLE
launchd-docs

### PR DESCRIPTION
**Pull request by mikedodge04**
Added documentation for the new launchd provider that is being reviewed here: https://github.com/chef/chef/pull/4111

### CODE REVIEW

**Comment by jamescott** [comment]
Hi Mike,

This will be in chef-client 12.7 release?

**Comment by mikedodge04** [comment]
@jamescott I'm still waiting to hear about (chef/chef#4111), maybe you can help me?

**Comment by jamescott** [comment]
I'm gonna wait to update this until the chef#4111 calms down a bit more. I have some questions about the Ruby types for the Apple-specific parameters (they don't seem to match up -- but that may well be as intended). Once that PR is set for approval, I'll finish up the doc for this. No worries.

**Comment by jamescott** [comment]
https://docs.chef.io/release/12-8/resource_launchd.html

^^ current draft for 12-8

**Comment by natewalck** [comment]
@jamescott , It looks like some wires are crossed.

**resource_osx_profile** is completely different from **resource_launchd**.

It looks like some terminology and actions from **osx_profile**: https://docs.chef.io/release/12-7/resource_osx_profile.html

Ended up in the documentation for **resource_launchd**:

https://docs.chef.io/release/12-8/resource_launchd.html

A **launchd** is _not_ a configuration profile. It is a completely different resource. The way it is referred to in this PR is correct (  "...resource to manage launchd daemons / agents") but in the documentation you linked, it says "A launchd resource to manage configuration profiles (.mobileconfig files) on the Mac OS X platform", which is **not** correct.

For instance:

resource_osx_profile is a .mobileconfig file

resource_launchd is a .plist file

A resource_launchd is a service like cron or upstart. It is not a configuration profile at all. It is a service.

Thanks for getting the docs updated! Let us know if any further clarification is needed.

**Comment by jamescott** [comment]
Here's the doc for launchd: https://docs.chef.io/release/12-8/resource_launchd.html

Please put any new issues or PRs on the `chef-web-docs` repo (note that this one has a `-2016` appended to it).

Thanks for the docs notes and the new resource!

james

**Comment by natewalck** [comment]
@jamescott I've made an issue on chef-web-docs (https://github.com/chef/chef-web-docs/issues/18). This **really** needs to be fixed. The docs do not match what Mike has in this PR, they were changed for some reason.

The docs submitted here were correct, so I am unsure why they got changed in the actual commit.

**Pull request closed without merging**
