### PR TITLE
Stop using default/

### PR DESCRIPTION
**Pull request by coderanger**
This is all 12.5-specific anyway, might as well stop.

### CODE REVIEW

**Comment by jamescott** [comment]
@delivery review

**Comment by chef-delivery** [comment]
Failed to review change: bb773805-15fe-4dcd-8715-c42ddc1e985f @jamescott

**Comment by coderanger** [comment]
I'm going to guess that's not something I can fix?

**Comment by jamescott** [comment]
Hmm, yeah. It's the Delivery integration. 

https://github.com/chef/chef-web-docs/pull/698

**Comment by jamescott** [comment]
It's merged, so should get picked up. I'll keep an eye on this one for you. Thanks for submitting!

james

**Comment by jamescott** [comment]
Is fixed:

https://docs.chef.io/custom_resources.html#create-templates

Thanks Noah.

**Pull request closed without merging**
