### PR TITLE
OMG PROVIDER DOCS BAD

### PR DESCRIPTION
**Pull request by lamont-granquist**
Most of the provider documentation is still for Chef 10.x, this is a major update that fixes:
- use_inline_resources everywhere
- proper use of conditional-wrapping-converge_by blocks everywhere
- ripping out explicitly setting updated_by_last_action which is now always wrong

Also fixed:
- simplification of irrelevant complexity in all the (poor) examples
- removed sections that were just trying to teach ruby coding (require, conditionals, rescue, etc) because both this was already enough of a yak shave, that problem is book-sized and completely open-ended and its just irrelevant distractions when looking for information on LWRPs
- fixed some wording around converge_by where the description is rendered both in non-why-run and why-run mode, the point of converge_by is to NOP the enclosing block in why-run mode.
- lots of use of single quotes around interpolated strings which is broken ruby.  IMO the entire docs 'codebase' should switch from single-quotes to double-quotes.  i know how this happened which is that someone made the argument that we should use 'root' instead of "root" because that's a common best practice, but then 'update #{foo}' becomes broken when that is blindly applied (which is IMO why that's a bad best practice).

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@jamesc @tas50 lets get this merged please, the existing docs are frighteningly bad here between all the broken code, non idempotent code, chef 10.x era code, irrelevant distractions, etc.

**Comment by lamont-granquist** [comment]
I also killed a ton of @-signs in the code to correctly use new_resource and current_resource accessors.  The only remaining @-signs should be in `@current_resource =` statements where its necessary.

**Comment by lamont-granquist** [comment]
If you find typos, please just push to this branch and fix it.

**Comment by tas50** [comment]
This is a pretty big one to get merged for our users.  I've been doing things wrong for a while apparently since I learned how do a lot of this from our docs.

**Comment by jamescott** [comment]
https://github.com/chef/chef-web-docs/commit/a3986da04f572da8502d358514e90e8fec5ca413

**Pull request closed without merging**
