### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: ad88f3fe-d8a8-4ab8-9194-255adae4e207 approved by: @jamescott

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
