### PR TITLE
Added documentation for the osx_profiles provider

### PR DESCRIPTION
**Pull request by natewalck**
Added documentation for the new osx_profiles provider that is being reviewed here: https://github.com/chef/chef/pull/4078

### CODE REVIEW

**Comment by natewalck** [comment]
Let me know if this documentation needs any further changes. Thank!

**Comment by jamescott** [comment]
@natewalck Nice job on the PR! I had to merge it differently, but here's the first build of the osx_profile resource: https://docs.chef.io/release/12-7/resource_osx_profile.html ... when 12.7 releases, I'll do a couple of things to move it to the main nav tree/collection. It's also in the release_notes.html for that collection as well.

I added two properties. Please review the descriptions for the actions/properties to make sure I didn't infer anything incorrectly. I also hooked in all the common properties that are true for all resources.

james

**Comment by natewalck** [comment]
@jamescott Awesome, thanks so much! I'll take a look at it and let you know.

Also, I think it was tagged for a minor release, so will it hit 12.6.1 or is it going directly from 12.6 to 12.7 with no dot release?

**Comment by jamescott** [comment]
I think it's 12.7, but if it does get into 12.6, then I'll just move some files and it'll get moved to 12.6 :)

**Comment by natewalck** [comment]
@jamescott For the properties:

```
profile 
Ruby Types: String, Hash

Use to specify one (or more) profiles.
```

This should be "Use to specify one profile." This is strictly one profile. It can be either the name of a profile within the cookbook or a hash with the profile contents in it. 

Also, `path` is automatically set and won't work if specified manually, I just realized. If that could be removed entirely that would be good.

**Comment by jamescott** [comment]
Am rebuilding to edit the `profile` description and remove `path`.

**Comment by natewalck** [comment]
Sorry, I just realized another thing to fix:

Use the osx_profile resource to manage configuration profiles (.profile files) on the Mac OS X platform. The osx_profile resource uses the profiles command to generate a unique ProfileUUID, and then ensure the profile is installed on the system or to remove the named profile from the system.

Instead, it should be:

Use the osx_profile resource to manage configuration profiles (.mobileconfig files) on the Mac OS X platform. The osx_profile resource uses the uuidgen library to generate a unique ProfileUUID, and then uses the profiles command to ensure the profile is installed on the system or to remove the named profile from the system.

**Comment by jamescott** [comment]
... and rebuilt!

**Comment by jamescott** [comment]
closing out as done

https://docs.chef.io/resource_osx_profile.html

**Pull request closed without merging**
