### PR TITLE
cron: minor fixes

### PR DESCRIPTION
**Pull request by goblin**
Two minor fixes to the "cron" resource documentation.

Another thing, as maplebed pointed on IRC, would be to add some example for the `command` attribute, but I'm not sure what example would be good.

### CODE REVIEW

**Comment by jamescott** [comment]
I will make the changes locally for the asterisks needing quoting as strings and the default '*' issue. The "Merge pull request #1" I am not sure what that is trying to do and there are far to many changes in that commit to take in a single pull request.

**Comment by goblin** [comment]
Thanks, that "merge" commit was me trying to sync up digital-science's clone to upstream... everything on it should already be in opscode master.

This pullreq was basically about these 2 commits that you said you'll include - which is OK :-) thanks

**Comment by jamescott** [comment]
Cool!

Thanks for the pull requests. I am asking around to see if anyone can help me find a better example for the cron resource's command attribute.

James

**Comment by jamescott** [comment]
OK. Some examples (quickly published), but hopefully they help provide more insight into what the command attribute can do within the context of the cron resource.

http://docs.opscode.com/resource_cron.html

James

---

From: James Scott
Sent: Thursday, March 21, 2013 1:55 PM
To: opscode/chef-docs
Subject: RE: [chef-docs] cron: minor fixes (#50)

Cool!

Thanks for the pull requests. I am asking around to see if anyone can help me find a better example for the cron resource's command attribute.

James

**Pull request closed without merging**
