### PR TITLE
change pointers and stuff for chef-client 12.5 release

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 25f138e6-345f-4e41-bcbb-72c26a65c649 approved by: @jamescott

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jamescott** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Failed to deliver change: 25f138e6-345f-4e41-bcbb-72c26a65c649
  Change is already delivered. @jamescott

**Pull request merged**
