### PR TITLE
Missing words in env_run_list msgs/warning

### PR DESCRIPTION
**Pull request by thorduri**

### CODE REVIEW

**Comment by jamescott** [comment]
Good catch! I fixed it here:

https://github.com/opscode/chef-docs/commit/ccabcd00074ae2ae8c65733880059bcebc7260a0

and will rebuild the entire /translate tree (which will fix the other string you noted).

james

**Comment by thorduri** [comment]
Welp. Should have studied that structure a bit better.

Anyways, thanks !

./ciao, thorduri.

On Wed, Jul 2, 2014 at 7:06 PM, jamescott notifications@github.com wrote:

> Good catch! I fixed it here:
> 
> ccabcd0
> https://github.com/opscode/chef-docs/commit/ccabcd00074ae2ae8c65733880059bcebc7260a0
> 
> and will rebuild the entire /translate tree (which will fix the other
> string you noted).
> 
> james
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/opscode/chef-docs/pull/289#issuecomment-47805969.

## 

/ciao, thorduri.

**Comment by jamescott** [comment]
n/p -- it's an easy one to miss. I'll have that other part updated in about ~20 minutes and then I'll close this bug out. Thanks for the pull request!

**Comment by jamescott** [comment]
Here's the /translate file update:

https://github.com/opscode/chef-docs/commit/d26c7c5e981e47ef08a4e4c4b856b6232fd26047

james

**Pull request closed without merging**
