### PR TITLE
https://github.com/chef/chef-web-docs/pull/707

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 02119578-8697-43e4-ae76-999a99fd15b7 approved by: @jamescott

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jamescott** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 02119578-8697-43e4-ae76-999a99fd15b7 delivered by: @jamescott

**Pull request merged**
