### PR TITLE
Document effect of strict_search_result_acls on manage

### PR DESCRIPTION
**Pull request by jcreedcmu**

### CODE REVIEW

**Comment by mmzyk** [comment]
Might want to be clear that chef-server-ctl reconfigure needs to be run first so the change is applied to the server, then a chef-manage-ctl reconfigure will pick it up.

**Comment by mmzyk** [comment]
I suppose I should note that the setting is already released for the chef server, however a version of Manage that can take care of it has not yet been released.

**Comment by jamescott** [comment]
@mmzyk  We're gonna merge this after the Manage piece is released.

**Comment by jcreedcmu** [comment]
This landed in 1.18.0, so I believe this (or whatever revision of it you find appropriate) can be merged.

**Pull request merged**
