### PR TITLE
document remote_file breaking change

### PR DESCRIPTION
**Pull request by danielsdeleo**
I tried to build the docs and verify that the tags linked correctly but I couldn't find the html version of the file I built. Anyway, the text itself is good so it should be enough to make the change on your own if I did something that doesn't work.

### CODE REVIEW

**Comment by sethvargo** [comment]
... sorry I'm late on this, but can we just _not_ break the resource in Chef 11? It seems that the most common use case for a remote file is a single url, not multiple paths with mirrors...

**Comment by sethvargo** [comment]
Can't the resource do a good old:

``` ruby
sources = [new_resource.source].flatten
```

That will ensure it's an array, regardless of whether it's a String or Array originally.

**Comment by danielsdeleo** [comment]
@sethvargo remote file itself works fine without any changes to cookbooks. It's only subclasses where the provider expects `RemoteFile#source` to return a String that will break

**Comment by sethvargo** [comment]
Ah gotcha. Sorry, I misunderstood. Nevermind then :smile:

**Comment by sethvargo** [comment]
@danielsdeleo The way it's written (without any context of where it is in the docs), it sounds like the `remote_file` resource has actually been changed to require `source` be an array. 

> As a result, the `source` parameter of the remote file resource is now an Array.

Maybe something like:

> As a result, the `source` attribute of a remote file resource now returns an Array.

Thoughts? I just don't want a user to think they need to change all their `remote_file` declarations.

**Comment by danielsdeleo** [comment]
I guess my doc update should be more clear. When creating a remote file resource, you can pass in a single URL or multiple URLs as `*args` and I think also an Array. This is then converted to an Array internally. Users of the `remote_file` resource itself are not affected by this change, except perhaps if they do something like

``` ruby
r = remote_file "/tmp/foo" do
  source "https://server.org/file"
end

if r.source == "https://server.org/file"
 # etc.
end
```

Anyway, you're right, this does need to be clear that it's the **getter** where you see the change and this is probably only relevant for library code that subclasses remote file.

**Comment by sethvargo** [comment]
Yea, I think using slightly different language and clearly indicating it **doesn't** affect the _use_ of `remote_file` would help a lot.

**Comment by danielsdeleo** [comment]
This?

**Comment by sethvargo** [comment]
:+1:

**Comment by danielsdeleo** [comment]
@sethvargo thanks for the review.

**Comment by danielsdeleo** [comment]
http://chef-docs.s3-website-us-east-1.amazonaws.com/release_chef_11.html#remote-file-mirror-support-may-break-subclasses

**Comment by danielsdeleo** [comment]
This is fixed even though github doesn't know about it.

**Pull request closed without merging**
