### PR TITLE
fix lwrp_aws link anchor

### PR DESCRIPTION
**Pull request by d-higuchi**

### CODE REVIEW

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/86aa2d0a4da3754792264183d4b0c66d54238553

and

https://github.com/opscode/chef-docs/commit/cfb3289296ac5b2215eb0f49dac65ec39ceaaa8c

Should be fixed now!

**Comment by d-higuchi** [comment]
thank you for your works, but link also should be updated from aws.html to lwrp_aws.html.

**Comment by jamescott** [comment]
Yes, I missed that one. Rebuilding! ;)

**Comment by jamescott** [comment]
OK, this should get it.

https://github.com/opscode/chef-docs/commit/1ba2e88ae886c0b1aeb40b9483c0aab30fea57b8

**Comment by d-higuchi** [comment]
thanks!

**Pull request closed without merging**
