### PR TITLE
correct azure mp docs to include analytics

### PR DESCRIPTION
**Pull request by andrewelizondo**
analytics is configured on our azure marketplace image, and should be highlighted in the documentation.

### CODE REVIEW

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Failed to approve change: bb773805-15fe-4dcd-8715-c42ddc1e985f
  Change must pass verify before approving. @jamescott

**Comment by jamescott** [comment]
@delivery verify

**Comment by chef-delivery** [comment]
Failed to unknown change: bb773805-15fe-4dcd-8715-c42ddc1e985f
  Delivery does not understand this command. @jamescott

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Failed to approve change: bb773805-15fe-4dcd-8715-c42ddc1e985f
  Change must pass verify before approving. @jamescott

**Pull request merged**
