### PR TITLE
Add the powershell wrapper documentation to chef 12.4 rel notes.

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by ksubrama** [comment]
@jamescott I did some things....  unfortunately my Mac's currently busted and I didn't feel like fighting with Make windows...  so..  :8ball:

**Comment by ksubrama** [comment]
Also /cc @jeremiahsnapp

**Comment by jamescott** [comment]
https://github.com/chef/chef-docs/commit/bf192b855e66c9c5d6575d44d1c24e8738569507

and

https://github.com/chef/chef-docs/commit/76fdf96a4f22c2fce839d9dc67c70cd3937f3b67

I put it in a few spots. The first one there is the actual words. If it looks good, feel free to close this one out as fixed.

**Comment by ksubrama** [comment]
Looks good!  Thank you!

**Pull request closed without merging**
