### PR TITLE
Add a README file

### PR DESCRIPTION
**Pull request by pierreozoux**

### CODE REVIEW

**Comment by jgoulah** [comment]
++ 
trying to get the docs working without this was a major pain

**Comment by jgoulah** [comment]
@pierreozoux one change,  you could just give compile instructions using the makefile:
    make release

**Comment by miketheman** [comment]
@pierreozoux I suspect that @jamescott went ahead and created a README since this was opened.

**Comment by jamescott** [comment]
True. We have a readme file now. We also have the docs.opscode.com/style_guide.html that talks a bit about how we're using Sphinx and the restructured text patterns in the source files.

**Pull request closed without merging**
