### PR TITLE
edit for 11.x vs. 12.x symlink paths

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by jamescott** [comment]
@delivery review

**Comment by chef-delivery** [comment]
Failed to review change: 77cc1f78-1f55-4245-a9ac-2ed7ae41e1cb @jamescott

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
