### PR TITLE
Add opscode-manage-ctl reconfigure

### PR DESCRIPTION
**Pull request by jcreedcmu**
To address https://github.com/chef/chef-manage-issues/issues/82

### CODE REVIEW

**Comment by mmzyk** [comment]
@jcreedcmu Does re-running the reconfigure ensure the secrets file is created correctly? I think it's actually applying it correctly.

**Comment by jcreedcmu** [comment]
That's my understanding of what https://github.com/chef/chef-manage-issues/issues/82 said --- can you clarify your reasons for thinking otherwise, if any?

**Comment by mmzyk** [comment]
In a multi-machine setup, what is happening is manage is being setup correctly on the first machine - this establishes the secrets that now need to be shared by each machine. We don't have any kind of service discovery mechanism, so by copying the file the secrets are being passed around. The second reconfigure then on the second, third, etc. machine running manage isn't to create this file, but to pick up the file that was copied over so that it can be applied correctly to the running configuration.

@jeremiahsnapp or someone else from support should verify, but that is my understanding of the situation. Either way, the second reconfigure will fix the docs, I'm just being pedantic on why it's needed.

**Comment by jeremiahsnapp** [comment]
@jcreedcmu I would consider using this instead since rerunning `opscode-manage-ctl reconfigure` is not making sure the secrets.rb file is created correctly.

```
... and rerun ``opscode-manage-ctl reconfigure`` so the copied ``/etc/opscode-manage/secrets.rb`` file gets used correctly.
```

**Comment by jcreedcmu** [comment]
Done! Thanks for the information, @mmzyk and @jeremiahsnapp.

**Pull request merged**
