### PR TITLE
Add Ship Show podcast

### PR DESCRIPTION
**Pull request by nathenharvey**

### CODE REVIEW

**Comment by jamescott** [comment]
The arbitrary rules of chef-docs include "alphabetize that list until one knows better" ... so thanks!

**Comment by jamescott** [comment]
Also, close :)

https://github.com/chef/chef-docs/commit/21aa14a43cc0c81db14eb107071f0f7245945df8

**Comment by nathenharvey** [comment]
so long as we're all clear, "alphabetize == random sort", :)

the order is "better" now

**Comment by jamescott** [comment]
@nathenharvey Image? Thumbs up or thumbs down:

https://github.com/chef/chef-docs/commit/5053f80dfc2080c2782575b8da6dad8e01c0417b

**Pull request merged**
