### PR TITLE
Jscott/editcustomresourcesforcoreresourceatributes

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jamescott** [comment]
@delivery accept

**Comment by chef-delivery** [comment]
Failed to unknown change: a7c8e4c9-7fb1-404e-a7e6-ac871ee09391
  Delivery does not understand this command. @jamescott

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: a7c8e4c9-7fb1-404e-a7e6-ac871ee09391 approved by: @jamescott

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
