### PR TITLE
update settings

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: bf474a5f-56ed-42cc-adea-400bd32ff74f approved by: @jamescott

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Failed to approve change: bf474a5f-56ed-42cc-adea-400bd32ff74f
  Change is already merged. @jamescott

**Comment by jamescott** [comment]
@delivery dosomething

**Comment by chef-delivery** [comment]
Failed to unknown change: bf474a5f-56ed-42cc-adea-400bd32ff74f
  Delivery does not understand this command. @jamescott

**Pull request merged**
