### PR TITLE
fix chef-docs #655

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jamescott** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: f23a803a-655b-4ab3-820f-e2ba670f7f0b approved by: @jamescott

**Comment by jamescott** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Failed to deliver change: f23a803a-655b-4ab3-820f-e2ba670f7f0b
  Change is already delivered. @jamescott

**Comment by jamescott** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Failed to deliver change: f23a803a-655b-4ab3-820f-e2ba670f7f0b
  Change is already delivered. @jamescott

**Pull request merged**
