### PR TITLE
Lcg/simply defintions

### PR DESCRIPTION
**Pull request by lamont-granquist**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@jamescott this is more like how it should look

**Comment by lamont-granquist** [comment]
- nothing has changed in 12.4/12.5 about definitions so this is all backcompat
- there's the one change in 12.0 about definitions now correctly returning their values
- i changed some code in the example to update it and make it a bit better (it would have 3694 error'd before, it now accepts running without an argument, returns the template resource on Chef 12, etc)
- dropped most of the overly complicated definition examples, and just showed how to convert the last definition example in the example section to a resource, which should be vastly clearer.

**Comment by jamescott** [comment]
Thanks @lamont-granquist ... I'll resolve the merge conflict ;) (it's my fault)

**Comment by lamont-granquist** [comment]
Yep all yours now....

One thing to note I caught you doing this quite a few times:

``` ruby
'stuff #{variable}'
```

Which doesn't actually work since single quotes don't support interpolation.  Those need to get fixed to:

``` ruby
"stuff #{variable}"
```

Which may be a pattern that is elsewhere in the docs, as well, I didn't go digging.

**Comment by lamont-granquist** [comment]
(and you can see how once I fixed the syntax highlighting the color of the `#{variable}` section changes with the different quotes around it)

**Comment by jamescott** [comment]
OK, two things:

https://github.com/chef/chef-docs/pull/632

Incorps the edited stuff. The updated definition => resource example is in the file _xxxxx and I still need to take another look at it and hook some stuff in.

**Pull request closed without merging**
