### PR TITLE
Simplify the definition of what a resource actually is.

### PR DESCRIPTION
**Pull request by juliandunn**
:construction_worker: 

@jamescott Per our discussion in HipChat, this is my first crack at simplifying the language that defines what a resource actually is. Feedback is welcome.

### CODE REVIEW

**Comment by jamescott** [comment]
Here's my first edit, trying to tighten it up:

"A resource defines some (or all) of the configuration settings that are necessary for a node that is under management by |chef| to be put into the desired state. During every |chef client| run, the current state of the node is tested, after which the |chef client| will take any steps that are necessary to repair that node and to bring it into the desired state."

**Comment by juliandunn** [comment]
The statement "A resource defines some (or all) of the configuration settings that are necessary for a node that is under management by |chef| to be put into the desired state" is not entirely accurate, because what you're describing is actually the entire contents of the Chef `run_list`. A resource in Chef actually maps to a configuration item on the system and its desired characteristics.

**Comment by jamescott** [comment]
OK, here's an edit to the run-list overview:

https://github.com/opscode/chef-docs/commit/2535da91b1c727439b8a65a3e91109870dbeba12

revising the resource overview again now.

**Comment by jamescott** [comment]
Revised resource overview:

"A resource defines the desired state for a single configuration item present on a node that is under management by |chef|. A resource collection---one (or more) individual resources---defines the desired state for the entire node. During every |chef client| run, the current state of each resource is tested, after which the |chef client| will take any steps that are necessary to repair the node and bring it back into the desired state."

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/d43ee5f12991e4c1c888388dc14e2531513f4889

I need to bring this into the main resource overview, after we've got this generic locked down. (Note -- this is the one that's at the top of all the standalone resource pages.)

**Comment by juliandunn** [comment]
:thumbsup: to the revised [resource overview definition](https://github.com/opscode/chef-docs/pull/265#issuecomment-41928605).

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/adea24de3a533f1c0ad356e5737faea0ee278013

This issue can be closed (no PR).

**Pull request closed without merging**
